// constants/actionTypes.js - User constants.
// Copywrite (C) 2018, Brett Broadhurst
//

// Every action type for the whole application. 
export const types = {

	// User Action Types
	REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST",
	REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
	REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",
	
	AUTH_USER_REQUEST: "AUTH_USER_REQUEST",
	AUTH_USER_SUCCESS: "AUTH_USER_SUCCESS",
	AUTH_USER_FAILURE: "AUTH_USER_FAILURE",
	AUTH_USER_LOGOUT: "AUTH_USER_LOGOUT",
	
	SET_USER: "SET_USER",
	UPDATE_FIELD: "UPDATE_FIELD",

	// Bootcamp actions.
	BOOTCAMP_ENROLL: "BOOTCAMP_ENROLL",
	BOOTCAMP_QUIT: "BOOTCAMP_QUIT",
	BOOTCAMP_GET: "BOOTCAMP_GET",
	BOOTCAMP_LESSON_GET: "BOOTCAMP_LESSON_GET",
	BOOTCAMP_LESSON_COMPLETE: "BOOTCAMP_LESSON_COMPLETE",

	// Admin Action Types //
	// Bootcamp actions.
	CREATE_BOOTCAMP_REQUEST: "CREATE_BOOTCAMP_REQUEST",
	CREATE_BOOTCAMP_SUCCESS: "CREATE_BOOTCAMP_SUCCESS",
	CREATE_BOOTCAMP_FAILURE: "CREATE_BOOTCAMP_FAILURE",

	UPDATE_BOOTCAMP_REQUEST: "UPDATE_BOOTCAMP_REQUEST",
	UPDATE_BOOTCAMP_SUCCESS: "UPDATE_BOOTCAMP_SUCCESS",
	UPDATE_BOOTCAMP_FAILURE: "UPDATE_BOOTCAMP_FAILURE",

	DELETE_BOOTCAMP_REQUEST: "DELETE_BOOTCAMP_REQUEST",
	DELETE_BOOTCAMP_SUCCESS: "DELETE_BOOTCAMP_SUCCESS",
	DELETE_BOOTCAMP_FAILURE: "DELETE_BOOTCAMP_FAILURE",

	// Bootcamp Lesson actions.
	CREATE_LESSON_REQUEST: "CREATE_LESSON_REQUEST",
	CREATE_LESSON_SUCCESS: "CREATE_LESSON_SUCCESS",
	CREATE_LESSON_FAILURE: "CREATE_LESSON_FAILURE",
	
	UPDATE_LESSON_REQUEST: "UPDATE_LESSON_REQUEST",
	UPDATE_LESSON_SUCCESS: "UPDATE_LESSON_SUCCESS",
	UPDATE_LESSON_FAILURE: "UPDATE_LESSON_FAILURE",
	
	DELETE_LESSON_REQUEST: "DELETE_LESSON_REQUEST",
	DELETE_LESSON_SUCCESS: "DELETE_LESSON_SUCCESS",
	DELETE_LESSON_FAILURE: "DELETE_LESSON_FAILURE",
	
	GET_BOOTCAMP: "GET_BOOTCAMP",
	GET_BOOTCAMPS: "GET_BOOTCAMPS",
	GET_LESSON: "GET_LESSON",
	GET_LESSONS: "GET_LESSONS"
};
