// constants/actionTypes.js - User constants.
// Copywrite (C) 2018, Brett Broadhurst
//

export const types = {
	REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST",
	REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
	REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",
	AUTH_USER_REQUEST: "AUTH_USER_REQUEST",
	AUTH_USER_SUCCESS: "AUTH_USER_SUCCESS",
	AUTH_USER_FAILURE: "AUTH_USER_FAILURE",
	AUTH_USER_LOGOUT: "AUTH_USER_LOGOUT",
	UPDATE_FIELD: "UPDATE_FIELD"
};
